### ISSUE TITLE
getting error as java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by pallavkumar112** [microsoftgraph/msgraph-sdk-android-auth#8]
I am using latest ADAL lib intuneApi 'com.microsoft.aad:adal:1.16.3' and using the graph lib as mentioned in this document 'com.microsoft.graph:microsoft-graph-android-auth:0.1.0-SNAPSHOT'

I think there are some classes getting conflict as ADAL lib is the latest one and getting error as below: 
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/identity/common/internal/cache/AccountCredentialCache;
        at com.microsoft.identity.client.PublicClientApplication.initCommonCache(PublicClientApplication.java:1078)
        at com.microsoft.identity.client.PublicClientApplication.getOAuth2TokenCache(PublicClientApplication.java:1094)
        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:250)

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.

**Comment by baywet** [comment]
sorry, disregard the last comment, misfire.

**Comment by baywet** [comment]
Hi @pallavkumar112 
Thanks for reaching out and for the patience. With the release of the v3 of the java SDK, it now integrates with Azure Identity which supports a wide variety of authentication flows out of the box.
We strongly encourage you to migrate to this v3 + azure identity, and you can read more about it in this issue.
https://github.com/microsoftgraph/msgraph-sdk-java/issues/628

This issue won't be fixed, but I'll leave it open for visibility, and the repository will be archived soon.
